import type { Shot } from "../shots";
import { NEXT_STEPS, SEASON, brandCard, nextStepsCard, titleCard } from "./cards";
import {
  SceneKbAsk,
  SceneKbAttach,
  SceneKbCompile,
  SceneKbCreate,
  SceneKbSource,
  SceneKbWiki,
} from "./t02-add-knowledge";
import {
  SceneSkillAdd,
  SceneSkillAttached,
  SceneSkillEdit,
  SceneSkillExpert,
  SceneSkillTemplates,
  SceneSkillUse,
} from "./t03-add-skills";
import {
  SceneBuiltinTools,
  SceneMcpForm,
  SceneToolUse,
  SceneToolkits,
  SceneToolsTab,
} from "./t04-connect-tools";
import {
  SceneChannelsList,
  SceneSlackOptions,
  SceneSlackThread,
  SceneSlackWizard,
} from "./t05-put-it-in-slack";
import {
  SceneMissionDashboard,
  SceneMissionDone,
  SceneMissionInbox,
  SceneMissionStart,
  SceneMissionWorkers,
} from "./t06-hand-it-a-mission";
import {
  SceneBrowserAuth,
  SceneBrowserControl,
  SceneBrowserOpen,
  SceneBrowserProfiles,
} from "./browser-view";
import {
  SceneSessionFlag,
  SceneSessionThread,
  SceneSessionTools,
  SceneSessionsList,
} from "./t08-read-a-session";
import {
  SceneEditSoul,
  SceneEvaluate,
  SceneTrainToFix,
  SceneTriage,
  SceneVerified,
} from "./t09-correct-and-redeploy";
import {
  SceneResearchCapability,
  SceneResearchChain,
  SceneResearchCommand,
  SceneResearchReport,
} from "./t10-deep-research";
import {
  SceneResearchRun,
  SceneResearchRunCommand,
  SceneHeldOut,
  SceneIdeaTree,
  SceneMergeVerified,
} from "./t11-research-missions";
import {
  SceneCodeConnect,
  SceneCodeRepo,
  SceneCodeRun,
  SceneCodeRunCommand,
  SceneCodeSafety,
} from "./t12-coding-agents";
import {
  SceneLoopCadence,
  SceneLoopPage,
  SceneLoopSyntax,
  SceneLoopTick,
} from "./t13-loops";
import {
  SceneAnswerBox,
  SceneBoardContinue,
  SceneBoardWrite,
} from "./t14-whiteboard";
import {
  SceneGoalCommand,
  SceneGoalLoop,
  SceneGoalVerdicts,
  SceneGoalWhenNot,
} from "./t15-goals";
import {
  SceneGovernanceGate,
  SceneInboxKinds,
  SceneInboxList,
} from "./t16-approvals";
import {
  SceneEgress,
  SceneFrozenGate,
  SceneToolAccess,
  SceneTwoLayers,
} from "./t17-governance";
import {
  SceneAccessPatterns,
  SceneIdentityLink,
  SceneUsageLimits,
  SceneUsersTab,
} from "./t18-users";
import {
  SceneAgentUrl,
  SceneWebAccess,
  SceneWebApp,
} from "./t18-web-app";
import {
  SceneModelConfig,
  SceneModelForm,
  SceneModelPerformance,
  SceneModelPlayground,
  SceneModelServing,
  SceneModelSources,
} from "./t20-deploy-a-model";
import {
  SceneDatasetForm,
  SceneDatasetPipeline,
  SceneDatasetSamples,
  SceneDatasetReady,
  SceneDatasetSources,
} from "./t21-build-a-dataset";
import {
  SceneColumnTypes,
  SceneSyntheticFlow,
  SceneSyntheticForm,
  SceneSyntheticRun,
} from "./t23-synthetic";
import {
  SceneExperiment,
  SceneSftCheckpoints,
  SceneSftConfig,
  SceneSftDatasets,
  SceneSftHyper,
  SceneSftLineage,
  SceneSftRun,
  SceneSftSource,
} from "./t24-sft";
import {
  SceneRlCurve,
  SceneRlDeploy,
  SceneRlEnvironment,
  SceneRlForm,
  SceneRlMethod,
  SceneRlPayoff,
  SceneRlProblem,
  SceneRlRubric,
  SceneRlRollout,
  SceneRlRollouts,
  SceneRlRuler,
  SceneRlShip,
  SceneRlUseIt,
  SceneRlTune,
} from "./t25-rl-run";
import {
  SceneDistillCurve,
  SceneDistillLoss,
  SceneDistillMethod,
  SceneDistillPair,
  SceneDistillPayoff,
  SceneDistillProblem,
  SceneDistillTopK,
} from "./t26-distill";
import {
  SceneEvalCategories,
  SceneEvalConfigure,
  SceneEvalCatalogue,
  SceneEvalResult,
  SceneEvalReview,
  SceneEvalSelect,
} from "./t27-evaluate";
import {
  SceneComputeConnect,
  SceneComputeDefault,
  SceneComputeOffers,
  SceneComputePayoff,
  SceneComputeProviders,
  SceneComputeSsh,
} from "./t28-compute";
import {
  SceneHubCommits,
  SceneHubList,
  SceneHubPayoff,
  SceneHubRepo,
  SceneHubTags,
} from "./t29-hub";
import {
  SceneStripeAfter,
  SceneStripeBuyPage,
  SceneStripeChecklist,
  SceneStripeConnect,
  SceneStripeLive,
  SceneStripeOffer,
  SceneStripePricing,
} from "./t30-stripe";
import {
  SceneBuyLinkEmbed,
  SceneBuyLinkPage,
  SceneBuyLinkShare,
  SceneBuyLinkTheme,
  SceneIdentity,
  SceneLandingBlocks,
  SceneLandingLayouts,
  SceneLandingPublish,
  SceneLandingRendered,
} from "./t31-buy-link";
import {
  SceneBuyerActivating,
  SceneBuyerChat,
  SceneBuyerCheckout,
  SceneBuyerLand,
  SceneBuyerRenew,
  SceneBuyerSignIn,
} from "./t32-buyer";
import { SceneAgentsGrid, SceneChat, SceneTemplatesPage } from "./work-screens";
import {
  SceneAgentForm,
  SceneAgentOverview,
  SceneProvision,
} from "./t01-create-agent";

/**
 * The tutorial catalogue. See VIDEOS.md for the full plan.
 *
 * A tutorial differs from the showcase films in three ways: shots are long
 * enough to follow, every middle shot carries step chrome, and the cut opens on
 * a title and closes on the single next thing to do.
 */

/** 01 — Create your first agent from a template. ~1:30. */
export const T01_CREATE_AGENT: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Create your first agent",
      "From a template, in about a minute — no code.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "agents",
    duration: 5,
    scene: SceneAgentsGrid,
    step: 1,
    steps: 6,
    caption: "Open Agents, then Create agent",
    captionSub: "This page lists every agent in the project.",
    captionAt: "bottom-center",
    build: "The agents grid: search, status filter, create tile, running agents.",
  },
  {
    id: 3,
    name: "templates",
    duration: 5,
    scene: SceneTemplatesPage,
    step: 2,
    steps: 6,
    caption: "Pick a template",
    captionSub:
      "Describe what you need and the catalogue narrows, or start from an Empty Agent.",
    captionAt: "bottom-center",
    build: "The templates page: category chips, count, three template cards.",
  },
  {
    id: 4,
    name: "form",
    duration: 5,
    scene: SceneAgentForm,
    step: 3,
    steps: 6,
    caption: "Name it and say what it does",
    captionSub: "The URL fills itself in as you type the name.",
    captionAt: "bottom-center",
    build: "The new-agent form: name typed, slug auto-filling, description.",
  },
  {
    id: 5,
    name: "provision",
    duration: 5,
    scene: SceneProvision,
    step: 4,
    steps: 6,
    caption: "Create it",
    captionSub: "It takes about thirty seconds.",
    captionAt: "bottom-center",
    build: "CREATE AGENT pressed, progress bar, status flips to running.",
  },
  {
    id: 6,
    name: "overview",
    duration: 5,
    scene: SceneAgentOverview,
    step: 5,
    steps: 6,
    caption: "It's running",
    captionSub: "The overview page suggests what to set up next.",
    captionAt: "bottom-center",
    build: "The overview page: public URL, running badge, five next-step cards.",
  },
  {
    id: 7,
    name: "chat",
    duration: 5,
    scene: SceneChat,
    step: 6,
    steps: 6,
    caption: "Say hello",
    captionSub: "Right now it only knows what the base model knows.",
    captionAt: "bottom-center",
    build: "The chat: user bubble, a collapsed tool row, the reply, the composer.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "Twelve capability tiles landing together, then the tail line.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card: the logo and surogate.ai.",
  },
];

/** 02 — Give it your knowledge. */
export const T02_ADD_KNOWLEDGE: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Give it your knowledge",
      "So it answers from your documents, not from the internet.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "create",
    duration: 5,
    scene: SceneKbCreate,
    step: 1,
    steps: 6,
    caption: "Create a knowledge base",
    captionSub: "Pick the model that will read your documents.",
    captionAt: "bottom-center",
    build: "The create form: display name, slug, description, curator model.",
  },
  {
    id: 3,
    name: "source",
    duration: 5,
    scene: SceneKbSource,
    step: 2,
    steps: 6,
    caption: "Add your documents",
    captionSub: "It takes PDFs, Word files, Markdown, text and CSV.",
    captionAt: "bottom-center",
    build: "The source picker: File upload live, S3 and URL list coming soon.",
  },
  {
    id: 4,
    name: "compile",
    duration: 5,
    scene: SceneKbCompile,
    step: 3,
    steps: 6,
    caption: "Compile it",
    captionSub: "The curator reads everything and writes a wiki from it.",
    captionAt: "bottom-center",
    build: "Stat cards and the processing banner counting sources through.",
  },
  {
    id: 5,
    name: "wiki",
    duration: 5,
    scene: SceneKbWiki,
    step: 4,
    steps: 6,
    caption: "Read the wiki yourself",
    captionSub: "This is what the agent gets, and you can check it.",
    captionAt: "bottom-center",
    build: "The wiki: page list with search, and a synthesis page open.",
  },
  {
    id: 6,
    name: "attach",
    duration: 5,
    scene: SceneKbAttach,
    step: 5,
    steps: 6,
    caption: "Attach it to the agent",
    captionSub: "Grounding makes it cite sources. Reference just lets it look.",
    captionAt: "bottom-center",
    build: "Attaching the KB, then the three usage modes with what each means.",
  },
  {
    id: 7,
    name: "ask",
    duration: 5,
    scene: SceneKbAsk,
    step: 6,
    steps: 6,
    caption: "Ask it something",
    captionSub: "The answer comes with a link to where it found it.",
    captionAt: "bottom-center",
    build: "A question, the KB search, the answer, and the citation.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 03 — Give it skills. */
export const T03_ADD_SKILLS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Give it skills",
      "So it follows your procedure, not a generic one.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "add",
    duration: 5,
    scene: SceneSkillAdd,
    step: 1,
    steps: 6,
    caption: "Adding a skill",
    captionSub: "There's a catalogue, or you can write one yourself.",
    captionAt: "bottom-center",
    build: "The picker: template recommended, write from scratch, import.",
  },
  {
    id: 3,
    name: "templates",
    duration: 5,
    scene: SceneSkillTemplates,
    step: 2,
    steps: 6,
    caption: "The catalogue",
    captionSub: "254 of them, sorted by category.",
    captionAt: "bottom-center",
    build: "Categories, the template list, and the read-only preview.",
  },
  {
    id: 4,
    name: "edit",
    duration: 5,
    scene: SceneSkillEdit,
    step: 3,
    steps: 6,
    caption: "Edit it",
    captionSub: "The description is what the agent reads when deciding to use it.",
    captionAt: "bottom-center",
    build: "The skill form: name, description, trigger, content.",
  },
  {
    id: 5,
    name: "expert",
    duration: 5,
    scene: SceneSkillExpert,
    step: 4,
    steps: 6,
    caption: "Or give it its own model",
    captionSub: "The main model hands that kind of work over to it.",
    captionAt: "bottom-center",
    build: "The Is Expert switch, then model, iterations and allowed tools.",
  },
  {
    id: 6,
    name: "attached",
    duration: 5,
    scene: SceneSkillAttached,
    step: 5,
    steps: 6,
    caption: "Attach as many as you like",
    captionSub: "Each is your own copy. Detach it whenever.",
    captionAt: "bottom-center",
    build: "The attached list with Edit and Detach on every row.",
  },
  {
    id: 7,
    name: "use",
    duration: 5,
    scene: SceneSkillUse,
    step: 6,
    steps: 6,
    caption: "Now it follows your procedure",
    captionSub: "The skill fires on its trigger.",
    captionAt: "bottom-center",
    build: "A refund request, the skill firing, and the answer following it.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 04 — Connect your tools. */
export const T04_CONNECT_TOOLS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Connect your tools",
      "So it can act in your real systems, not just talk about them.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "builtin",
    duration: 5,
    scene: SceneBuiltinTools,
    step: 1,
    steps: 5,
    caption: "What it can already do",
    captionSub: "These ship with every agent.",
    captionAt: "bottom-center",
    build: "Editorial board: eight built-in capabilities with their real tool names.",
  },
  {
    id: 3,
    name: "tools-tab",
    duration: 5,
    scene: SceneToolsTab,
    step: 2,
    steps: 5,
    caption: "Adding your own",
    captionSub: "Your library, a ready-made toolkit, or any MCP server.",
    captionAt: "bottom-center",
    build: "The Tools tab: three cards and the key vault.",
  },
  {
    id: 4,
    name: "toolkits",
    duration: 5,
    scene: SceneToolkits,
    step: 3,
    steps: 5,
    caption: "Over a thousand toolkits",
    captionSub: "GitHub, Slack, Stripe. Attach one and it's connected.",
    captionAt: "bottom-center",
    build: "The toolkit catalog with search and per-row Attach.",
  },
  {
    id: 5,
    name: "mcp",
    duration: 5,
    scene: SceneMcpForm,
    step: 4,
    steps: 5,
    caption: "Or any MCP server",
    captionSub: "Keys go into the vault. The agent never sees them.",
    captionAt: "bottom-center",
    build: "The MCP form: name, endpoint, sign-in and the key.",
  },
  {
    id: 6,
    name: "use",
    duration: 5,
    scene: SceneToolUse,
    step: 5,
    steps: 5,
    caption: "Now it can do the thing",
    captionSub: "It calls the tool and reports what came back.",
    captionAt: "bottom-center",
    build: "A refund request, the stripe call, the result, the reply.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 05 — Put it in Slack. */
export const T05_PUT_IT_IN_SLACK: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Put it in Slack",
      "Your team talks to it where they already work.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "channels",
    duration: 5,
    scene: SceneChannelsList,
    step: 1,
    steps: 4,
    caption: "Pick a channel",
    captionSub: "Slack, Telegram, WhatsApp, or your own site.",
    captionAt: "bottom-center",
    build: "The Channels page: Web already live, the rest offering Connect.",
  },
  {
    id: 3,
    name: "wizard",
    duration: 5,
    scene: SceneSlackWizard,
    step: 2,
    steps: 4,
    caption: "Connect the workspace",
    captionSub: "Create the Slack app, then paste the token.",
    captionAt: "bottom-center",
    build: "The three wizard steps, then the App ID and bot token fields.",
  },
  {
    id: 4,
    name: "options",
    duration: 5,
    scene: SceneSlackOptions,
    step: 3,
    steps: 4,
    caption: "Decide when it speaks",
    captionSub: "Only when mentioned, or in whichever channels you name.",
    captionAt: "bottom-center",
    build: "The Slack options: mention, threading, free-response channels.",
  },
  {
    id: 5,
    name: "slack",
    duration: 5,
    scene: SceneSlackThread,
    step: 4,
    steps: 4,
    caption: "It's in the channel",
    captionSub: "Replies go in a thread, not the main channel.",
    captionAt: "bottom-center",
    build: "Slack: the ask sits in #support, the agent answers in the thread.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 06 — Hand it a mission. */
export const T06_HAND_IT_A_MISSION: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Hand it a mission",
      "Work that takes hours, finished while you are away.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "start",
    duration: 5,
    scene: SceneMissionStart,
    step: 1,
    steps: 5,
    caption: "Start one from any chat",
    captionSub: "Type /mission and describe the outcome you want.",
    captionAt: "bottom-center",
    build: "The composer typing a /mission command, with the slash menu open.",
  },
  {
    id: 3,
    name: "dashboard",
    duration: 5,
    scene: SceneMissionDashboard,
    step: 2,
    steps: 5,
    caption: "It plans the work itself",
    captionSub: "It writes the task list, then rewrites it as it goes.",
    captionAt: "bottom-center",
    build: "The mission dashboard: iterations, tabs, the tasks rail by status.",
  },
  {
    id: 4,
    name: "workers",
    duration: 5,
    scene: SceneMissionWorkers,
    step: 3,
    steps: 5,
    caption: "Work gets split across workers",
    captionSub: "Each one is its own run, with a session you can read.",
    captionAt: "bottom-center",
    build: "The workers tab: three workers, one done, one running, one queued.",
  },
  {
    id: 5,
    name: "inbox",
    duration: 5,
    scene: SceneMissionInbox,
    step: 4,
    steps: 5,
    caption: "It comes back when it's stuck",
    captionSub: "Answer, and it picks up where it stopped.",
    captionAt: "bottom-center",
    build: "The inbox: a worker asking which venue to book, with answer buttons.",
  },
  {
    id: 6,
    name: "done",
    duration: 5,
    scene: SceneMissionDone,
    step: 5,
    steps: 5,
    caption: "It knows when it's done",
    captionSub: "A rubric decides that, not an empty task list.",
    captionAt: "bottom-center",
    build: "Status satisfied, the verdict against the rubric, every task done.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 07 — Let it use a browser. */
export const T07_USE_A_BROWSER: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Let it use a browser",
      "Real pages, real clicks — and you can take the wheel.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "profiles",
    duration: 5,
    scene: SceneBrowserProfiles,
    step: 1,
    steps: 4,
    caption: "Give it a browser profile",
    captionSub: "Cookies and logins stick around between runs.",
    captionAt: "bottom-center",
    build: "The Browser Profiles page, adding one for supplier logins.",
  },
  {
    id: 3,
    name: "auth",
    duration: 5,
    scene: SceneBrowserAuth,
    step: 2,
    steps: 4,
    caption: "Sign in once, yourself",
    captionSub: "You type the password. It gets the session, never the password.",
    captionAt: "bottom-center",
    build: "The auth dialog: a live browser you log into by hand, then save.",
  },
  {
    id: 4,
    name: "open",
    duration: 5,
    scene: SceneBrowserOpen,
    step: 3,
    steps: 4,
    caption: "Ask it to go and look",
    captionSub: "A real browser opens and you watch it work.",
    captionAt: "bottom-center",
    build: "The pane connecting, the page arriving, the first lines streaming.",
  },
  {
    id: 5,
    name: "control",
    duration: 5,
    scene: SceneBrowserControl,
    step: 4,
    steps: 4,
    caption: "Take over any time",
    captionSub: "One click and the page is yours.",
    captionAt: "bottom-center",
    build: "Control taken: the pointer fills amber and the pill appears.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 08 — Read a session. */
export const T08_READ_A_SESSION: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Read a session",
      "See exactly what it did — and where it went wrong.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "list",
    duration: 5,
    scene: SceneSessionsList,
    step: 1,
    steps: 4,
    caption: "Find the one that went wrong",
    captionSub: "Filter by thumbs-down, denied tools, crashes, overrides.",
    captionAt: "bottom-center",
    build: "The sessions list, filtering down to the one thumbed down.",
  },
  {
    id: 3,
    name: "thread",
    duration: 5,
    scene: SceneSessionThread,
    step: 2,
    steps: 4,
    caption: "Read the whole thing",
    captionSub: "Every turn and every tool call is kept.",
    captionAt: "bottom-center",
    build: "The review thread: the ask, the tool chips, the wrong answer.",
  },
  {
    id: 4,
    name: "tools",
    duration: 5,
    scene: SceneSessionTools,
    step: 3,
    steps: 4,
    caption: "Open the call that broke it",
    captionSub: "Arguments and result, in full.",
    captionAt: "bottom-center",
    build: "The tools table, the web_extract result, and the stale page.",
  },
  {
    id: 5,
    name: "flag",
    duration: 5,
    scene: SceneSessionFlag,
    step: 4,
    steps: 4,
    caption: "Flag it",
    captionSub: "Flagged sessions become the set you re-run later.",
    captionAt: "bottom-center",
    build: "What a thumbs-down buys you: a chip, a regression set, a re-check.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 09 — Correct it and redeploy. */
export const T09_CORRECT_AND_REDEPLOY: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Correct it and redeploy",
      "Close the loop on the thing you just found.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "triage",
    duration: 5,
    scene: SceneTriage,
    step: 1,
    steps: 5,
    caption: "Work out what to change",
    captionSub: "There are four places the problem can live.",
    captionAt: "bottom-center",
    build: "The triage: wrong facts, wrong procedure, no access, wrong identity.",
  },
  {
    id: 3,
    name: "soul",
    duration: 5,
    scene: SceneEditSoul,
    step: 2,
    steps: 5,
    caption: "Make the change",
    captionSub: "SOUL.md is for who it is, not how it does one task.",
    captionAt: "bottom-center",
    build: "The Identity tab: a rule typed in, the unsaved-changes banner.",
  },
  {
    id: 4,
    name: "verified",
    duration: 5,
    scene: SceneVerified,
    step: 3,
    steps: 5,
    caption: "Ask again",
    captionSub: "This time it checks the knowledge base.",
    captionAt: "bottom-center",
    build: "Same question, kb_search_pages instead of the web, thumbs up.",
  },
  {
    id: 5,
    name: "train",
    duration: 5,
    scene: SceneTrainToFix,
    step: 4,
    steps: 5,
    caption: "Some things a rule won't fix",
    captionSub: "That's when you train instead.",
    captionAt: "bottom-center",
    build: "The four training methods, SFT selected.",
  },
  {
    id: 6,
    name: "evaluate",
    duration: 5,
    scene: SceneEvaluate,
    step: 5,
    steps: 5,
    caption: "Then check it worked",
    captionSub: "Same benchmark, before and after.",
    captionAt: "bottom-center",
    build: "The benchmark catalogue, and the before/after score.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 10 — Deep research. */
export const T10_DEEP_RESEARCH: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Deep research",
      "A sourced answer to a question worth an afternoon.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "capability",
    duration: 5,
    scene: SceneResearchCapability,
    step: 1,
    steps: 4,
    caption: "Turn it on",
    captionSub: "Capabilities decide what the agent offers at all.",
    captionAt: "bottom-center",
    build: "The Capabilities tab, flipping the deep-research workflow on.",
  },
  {
    id: 3,
    name: "command",
    duration: 5,
    scene: SceneResearchCommand,
    step: 2,
    steps: 4,
    caption: "Give it the question",
    captionSub: "You don't have to tell it how to research.",
    captionAt: "bottom-center",
    build: "The slash palette, then /deep-research with a topic typed in.",
  },
  {
    id: 4,
    name: "chain",
    duration: 8,
    scene: SceneResearchChain,
    step: 3,
    steps: 4,
    caption: "It splits the work",
    captionSub: "A researcher gathers, a writer writes it up.",
    captionAt: "bottom-center",
    build: "The delegation chain, and the single-shot cap.",
  },
  {
    id: 5,
    name: "report",
    duration: 5,
    scene: SceneResearchReport,
    step: 4,
    steps: 4,
    caption: "You get a report",
    captionSub: "Every claim has a citation you can open.",
    captionAt: "bottom-center",
    build: "The report with [S#] chips, and the sources strip beneath it.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 11 — Research missions. */
export const T11_RESEARCH_MISSIONS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Research missions",
      "An optimisation run that improves your agent for you.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "arbor",
    duration: 5,
    scene: SceneResearchRun,
    step: 1,
    steps: 5,
    caption: "It experiments on its own",
    captionSub: "Each idea is tested by itself and kept only if it wins.",
    captionAt: "bottom-center",
    build: "What a research run does, in four moves.",
  },
  {
    id: 3,
    name: "command",
    duration: 5,
    scene: SceneResearchRunCommand,
    step: 2,
    steps: 5,
    caption: "Give it a repo and a rubric",
    captionSub: "It won't start without both.",
    captionAt: "bottom-center",
    build: "The /auto-research command, its tokens, and the rubric requirement.",
  },
  {
    id: 4,
    name: "tree",
    duration: 8,
    scene: SceneIdeaTree,
    step: 3,
    steps: 5,
    caption: "Ideas branch off each other",
    captionSub: "Every one is scored against the baseline.",
    captionAt: "bottom-center",
    build: "The idea tree: nodes landing, running, then settling to done or pruned.",
  },
  {
    id: 5,
    name: "held-out",
    duration: 5,
    scene: SceneHeldOut,
    step: 4,
    steps: 5,
    caption: "The score that counts",
    captionSub: "The held-out set is the one it never tuned against.",
    captionAt: "bottom-center",
    build: "Dev versus held-out, and why the second is authoritative.",
  },
  {
    id: 6,
    name: "merge",
    duration: 5,
    scene: SceneMergeVerified,
    step: 5,
    steps: 5,
    caption: "Only proven gains survive",
    captionSub: "The rest gets pruned.",
    captionAt: "bottom-center",
    build: "Worktrees, pruning, and the merge gate.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 12 — Coding agents. */
export const T12_CODING_AGENTS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Coding agents",
      "Run Claude Code or Codex on your workspace, on your own plan.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "connect",
    duration: 5,
    scene: SceneCodeConnect,
    step: 1,
    steps: 5,
    caption: "Connect your own subscription",
    captionSub: "Stored per user and encrypted.",
    captionAt: "bottom-center",
    build: "Settings → Coding Agents, connecting Claude Code.",
  },
  {
    id: 3,
    name: "command",
    duration: 5,
    scene: SceneCodeRunCommand,
    step: 2,
    steps: 5,
    caption: "Hand it the task",
    captionSub: "Choose the model, the effort level, and whether it can write files.",
    captionAt: "bottom-center",
    build: "The /code command and its four flags.",
  },
  {
    id: 4,
    name: "run",
    duration: 8,
    scene: SceneCodeRun,
    step: 3,
    steps: 5,
    caption: "It runs the real CLI",
    captionSub: "You watch the output as it goes.",
    captionAt: "bottom-center",
    build: "The run block: Running claude…, streamed output, then Ran claude.",
  },
  {
    id: 5,
    name: "repo",
    duration: 5,
    scene: SceneCodeRepo,
    step: 4,
    steps: 5,
    caption: "Or point it at a repo",
    captionSub: "It branches, commits and opens a pull request.",
    captionAt: "bottom-center",
    build: "A --repo run: checkout, branch, commit, and the PR it opens.",
  },
  {
    id: 6,
    name: "safety",
    duration: 5,
    scene: SceneCodeSafety,
    step: 5,
    steps: 5,
    caption: "Your key stays in the sandbox",
    captionSub: "It goes into the process and comes straight back out.",
    captionAt: "bottom-center",
    build: "The four safeguards around the credential.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 13 — Loops. */
export const T13_LOOPS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard("Loops", "Work that runs without being asked."),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "syntax",
    duration: 5,
    scene: SceneLoopSyntax,
    step: 1,
    steps: 4,
    caption: "Write it however you like",
    captionSub: "It understands the interval wherever you put it.",
    captionAt: "bottom-center",
    build: "The three /loop forms, including the dynamic one.",
  },
  {
    id: 3,
    name: "cadence",
    duration: 5,
    scene: SceneLoopCadence,
    step: 2,
    steps: 4,
    caption: "Check what it actually set",
    captionSub: "Under an hour it snaps to a cadence that divides evenly.",
    captionAt: "bottom-center",
    build: "Requested against actual cadence, and which ones move.",
  },
  {
    id: 4,
    name: "page",
    duration: 5,
    scene: SceneLoopPage,
    step: 3,
    steps: 4,
    caption: "All your loops",
    captionSub: "You can see what's next and stop any of them.",
    captionAt: "bottom-center",
    build: "The Scheduled work page: the table, and the expiry note.",
  },
  {
    id: 5,
    name: "tick",
    duration: 5,
    scene: SceneLoopTick,
    step: 4,
    steps: 4,
    caption: "It stays quiet most of the time",
    captionSub: "Every tick is a real run. Most have nothing to say.",
    captionAt: "bottom-center",
    build: "Three ticks of a loop, one of which is worth telling you about.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 14 — The whiteboard. */
export const T14_WHITEBOARD: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "The whiteboard",
      "Write and draw instead of typing — and it answers on the board.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "write",
    duration: 5,
    scene: SceneBoardWrite,
    step: 1,
    steps: 3,
    caption: "Just write",
    captionSub: "It reads your handwriting once and remembers it.",
    captionAt: "bottom-center",
    build: "The board and its tool rail; ink drawn in, then the reading beneath.",
  },
  {
    id: 3,
    name: "answer-box",
    duration: 8,
    scene: SceneAnswerBox,
    step: 2,
    steps: 3,
    caption: "Leave a box for the answer",
    captionSub: "It fits the answer in, and the box disappears.",
    captionAt: "bottom-center",
    build: "An answer box placed, Answer pressed, then the box replaced.",
  },
  {
    id: 4,
    name: "continue",
    duration: 8,
    scene: SceneBoardContinue,
    step: 3,
    steps: 3,
    caption: "Keep going from there",
    captionSub: "Your handwriting and its answer in the same line.",
    captionAt: "bottom-center",
    build: "Brackets and an exponent hand-drawn around the answer, then a second box.",
  },
  {
    id: 5,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 6,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 15 — Goals. */
export const T15_GOALS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard("Goals", "It keeps working until the outcome is reached."),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "command",
    duration: 5,
    scene: SceneGoalCommand,
    step: 1,
    steps: 4,
    caption: "Say what done looks like",
    captionSub: "Write things a person could actually check.",
    captionAt: "bottom-center",
    build: "/goal with a rubric, and what makes a rubric evaluable.",
  },
  {
    id: 3,
    name: "loop",
    duration: 8,
    scene: SceneGoalLoop,
    step: 2,
    steps: 4,
    caption: "A second model marks its work",
    captionSub: "If it's not there yet, the feedback becomes the next prompt.",
    captionAt: "bottom-center",
    build: "Three turns, two sent back, the third satisfied.",
  },
  {
    id: 4,
    name: "verdicts",
    duration: 5,
    scene: SceneGoalVerdicts,
    step: 3,
    steps: 4,
    caption: "How a turn ends",
    captionSub: "Only one of the four keeps it going.",
    captionAt: "bottom-center",
    build: "The four verdicts, and the evidence requirement.",
  },
  {
    id: 5,
    name: "when",
    duration: 5,
    scene: SceneGoalWhenNot,
    step: 4,
    steps: 4,
    caption: "Not for every task",
    captionSub: "If there's no finish line, it just adds overhead.",
    captionAt: "bottom-center",
    build: "When to reach for a goal, and when to just ask.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 16 — Approvals and the inbox. */
export const T16_APPROVALS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Approvals and the inbox",
      "Nothing consequential happens unwatched.",
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "inbox",
    duration: 8,
    scene: SceneInboxList,
    step: 1,
    steps: 3,
    caption: "The inbox",
    captionSub: "Sorted by what's blocked. You can also just reply in the chat.",
    captionAt: "bottom-center",
    build: "The inbox: the list in triage order, the question answered in the detail pane.",
  },
  {
    id: 3,
    name: "gate",
    duration: 5,
    scene: SceneGovernanceGate,
    step: 2,
    steps: 3,
    caption: "Approving a tool call",
    captionSub: "You see the arguments before it sends them.",
    captionAt: "bottom-center",
    build: "A governance gate: the call, its arguments, Approve or Reject.",
  },
  {
    id: 4,
    name: "kinds",
    duration: 5,
    scene: SceneInboxKinds,
    step: 3,
    steps: 3,
    caption: "Not all of them block",
    captionSub: "Two stop the run, one it works around, two are just notifications.",
    captionAt: "bottom-center",
    build: "The five item kinds and what each one costs you.",
  },
  {
    id: 5,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 6,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 17 — Governance. First of Season 2. */
export const T17_GOVERNANCE: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Governance",
      "It cannot reach what you did not permit.",
      SEASON.safe,
    ),
    build: "Opening card — first of Run it safely.",
  },
  {
    id: 2,
    name: "layers",
    duration: 5,
    scene: SceneTwoLayers,
    step: 1,
    steps: 4,
    caption: "Two layers",
    captionSub: "Your policy can narrow the platform floor, never widen it.",
    captionAt: "bottom-center",
    build: "The platform floor and your policy, and how they compose.",
  },
  {
    id: 3,
    name: "tools",
    duration: 8,
    scene: SceneToolAccess,
    step: 2,
    steps: 4,
    caption: "Which tools it may use",
    captionSub: "Deny beats allow when both apply.",
    captionAt: "bottom-center",
    build: "Policy enforcement on, then the allowed and denied tool lists.",
  },
  {
    id: 4,
    name: "egress",
    duration: 5,
    scene: SceneEgress,
    step: 3,
    steps: 4,
    caption: "Where it may go",
    captionSub: "Nothing is reachable until you name it.",
    captionAt: "bottom-center",
    build: "The egress card: default deny plus per-domain rules.",
  },
  {
    id: 5,
    name: "frozen",
    duration: 5,
    scene: SceneFrozenGate,
    step: 4,
    steps: 4,
    caption: "It can't be talked out of it",
    captionSub: "The gate is fixed when the turn starts.",
    captionAt: "bottom-center",
    build: "A prompt-injection attempt hitting the frozen gate.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 18 — The agent's own web app. */
export const T18_WEB_APP: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "The agent's own web app",
      "A URL you can send someone, the moment it is running.",
      SEASON.safe,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "url",
    duration: 5,
    scene: SceneAgentUrl,
    step: 1,
    steps: 3,
    caption: "It already has a URL",
    captionSub: "Nothing to host. The address is set when you deploy.",
    captionAt: "bottom-center",
    build: "The Web card, its URL, and the rename caveat.",
  },
  {
    id: 3,
    name: "app",
    duration: 8,
    scene: SceneWebApp,
    step: 2,
    steps: 3,
    caption: "It's a whole app",
    captionSub: "People get their own chats, files and inbox.",
    captionAt: "bottom-center",
    build: "The hosted app: session sidebar, header with inbox, a chat, composer.",
  },
  {
    id: 4,
    name: "access",
    duration: 5,
    scene: SceneWebAccess,
    step: 3,
    steps: 3,
    caption: "Who can open it",
    captionSub: "Anyone, or only people you've invited.",
    captionAt: "bottom-center",
    build: "Anonymous against authorised, and the monetized guarantee.",
  },
  {
    id: 5,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 6,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 19 — Users and access. */
export const T18_USERS: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard("Users and access", "Decide who gets in.", SEASON.safe),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "patterns",
    duration: 5,
    scene: SceneAccessPatterns,
    step: 1,
    steps: 4,
    caption: "Who is it for?",
    captionSub: "Your team, named customers, open sign-up, or anyone.",
    captionAt: "bottom-center",
    build: "The four access patterns and what each one means.",
  },
  {
    id: 3,
    name: "tab",
    duration: 8,
    scene: SceneUsersTab,
    step: 2,
    steps: 4,
    caption: "Invite someone",
    captionSub: "This gets them the agent, not a seat in your studio.",
    captionAt: "bottom-center",
    build: "The Users tab: the sign-up switch, the list, and an invite sent.",
  },
  {
    id: 4,
    name: "link",
    duration: 8,
    scene: SceneIdentityLink,
    step: 3,
    steps: 4,
    caption: "Linking their Slack",
    captionSub: "The bot sends a code and they enter it once.",
    captionAt: "bottom-center",
    build: "Slack issuing the code on the left, the /link page consuming it on the right.",
  },
  {
    id: 5,
    name: "limits",
    duration: 5,
    scene: SceneUsageLimits,
    step: 4,
    steps: 4,
    caption: "One allowance each",
    captionSub: "Switching channel doesn't reset anyone's quota.",
    captionAt: "bottom-center",
    build: "The usage limit following the person across four channels.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 20 — Deploy any model. First of Season 3. */
export const T20_DEPLOY_A_MODEL: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Deploy any model",
      "Your hub, Hugging Face, OpenRouter, or any endpoint you already run.",
      SEASON.develop,
    ),
    build: "Opening card — first of Build and train it.",
  },
  {
    id: 2,
    name: "sources",
    duration: 5,
    scene: SceneModelSources,
    step: 1,
    steps: 6,
    caption: "Where the model comes from",
    captionSub: "Your hub, Hugging Face, OpenRouter, or a URL.",
    captionAt: "bottom-center",
    build: "The four deploy sources, Hugging Face chosen.",
  },
  {
    id: 3,
    name: "form",
    duration: 8,
    scene: SceneModelForm,
    step: 2,
    steps: 6,
    caption: "Pin the revision",
    captionSub: "A branch, a tag or a commit, so you can redeploy the same thing.",
    captionAt: "bottom-center",
    build: "The Hugging Face form filling in, Deploy enabling once the repo is set.",
  },
  {
    id: 4,
    name: "serving",
    duration: 5,
    scene: SceneModelServing,
    step: 3,
    steps: 6,
    caption: "It's serving",
    captionSub: "New chats pick it up. Ones already running keep the old model.",
    captionAt: "bottom-center",
    build: "The model detail: serving banner, tabs, stats, deployment info.",
  },
  {
    id: 5,
    name: "performance",
    duration: 5,
    scene: SceneModelPerformance,
    step: 4,
    steps: 6,
    caption: "How it's behaving",
    captionSub: "Throughput and latency over the window you pick.",
    captionAt: "bottom-center",
    build: "The Performance tab: period selector, five KPIs, four sparklines.",
  },
  {
    id: 6,
    name: "config",
    duration: 5,
    scene: SceneModelConfig,
    step: 5,
    steps: 6,
    caption: "Set the defaults",
    captionSub: "Temperature, top-p and the rest, with presets to start from.",
    captionAt: "bottom-center",
    build: "The Config tab: generation defaults left, serving parameters right.",
  },
  {
    id: 7,
    name: "playground",
    duration: 5,
    scene: SceneModelPlayground,
    step: 6,
    steps: 6,
    caption: "Try it first",
    captionSub: "Your prompt, and the parameters right there to change.",
    captionAt: "bottom-center",
    build: "The Playground: a prompt and reply, with the parameters panel.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 21 — Build a dataset. */
export const T21_BUILD_A_DATASET: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Build a dataset",
      "The work your agents already did, turned into training data.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "sources",
    duration: 5,
    scene: SceneDatasetSources,
    step: 1,
    steps: 5,
    caption: "Where the rows come from",
    captionSub: "Real chats, your own files, synthetic ones, or the Hub.",
    captionAt: "bottom-center",
    build: "The four dataset sources, From chats chosen.",
  },
  {
    id: 3,
    name: "form",
    duration: 8,
    scene: SceneDatasetForm,
    step: 2,
    steps: 5,
    caption: "Filter out the bad ones",
    captionSub: "No crashes, no denials, no thumbs-down. That's the default.",
    captionAt: "bottom-center",
    build: "The build form: name, agents, filters, format, and scrubbing PII.",
  },
  {
    id: 4,
    name: "ready",
    duration: 5,
    scene: SceneDatasetReady,
    step: 3,
    steps: 5,
    caption: "It's ready",
    captionSub: "Train on it, or turn the same rows into a benchmark.",
    captionAt: "bottom-center",
    build: "The dataset detail: stat tiles, the ready banner, details and quality.",
  },
  {
    id: 5,
    name: "samples",
    duration: 5,
    scene: SceneDatasetSamples,
    step: 4,
    steps: 5,
    caption: "Read it first",
    captionSub: "The actual prompt and reply pairs.",
    captionAt: "bottom-center",
    build: "The Samples tab: three prompt/reply rows.",
  },
  {
    id: 6,
    name: "pipeline",
    duration: 8,
    scene: SceneDatasetPipeline,
    step: 5,
    steps: 5,
    caption: "Add columns",
    captionSub: "Judge the rows, check them, or generate more.",
    captionAt: "bottom-center",
    build: "The Pipeline tab: seed columns, a judge and a validator, the type menu.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 23 — Generate synthetic training data. */
export const T23_SYNTHETIC: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Generate synthetic data",
      "Rows you did not have to write — and did not have to trust blindly.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "flow",
    duration: 5,
    scene: SceneSyntheticFlow,
    step: 1,
    steps: 4,
    caption: "One writes, another marks",
    captionSub: "Only the rows that clear the bar are kept.",
    captionAt: "bottom-center",
    build: "The three chips: teacher generates, judge scores, keep above threshold.",
  },
  {
    id: 3,
    name: "form",
    duration: 8,
    scene: SceneSyntheticForm,
    step: 2,
    steps: 4,
    caption: "Describe what you want",
    captionSub: "A brief, the models to use, and where the bar sits.",
    captionAt: "bottom-center",
    build: "The synthetic form: brief, teacher, judge, topics, samples, threshold.",
  },
  {
    id: 4,
    name: "run",
    duration: 8,
    scene: SceneSyntheticRun,
    step: 3,
    steps: 4,
    caption: "It builds the pipeline",
    captionSub: "Four columns, from what you just told it.",
    captionAt: "bottom-center",
    build: "The composed pipeline running, and the threshold rejecting a row.",
  },
  {
    id: 5,
    name: "column-types",
    duration: 8,
    scene: SceneColumnTypes,
    step: 4,
    steps: 4,
    caption: "Seven kinds of column",
    captionSub: "Three of them never call a model at all.",
    captionAt: "bottom-center",
    build: "Each addable column type, what it does, and what you configure.",
  },
  {
    id: 6,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 7,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** 24 — Fine-tune with SFT. */
export const T24_SFT: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Fine-tune with SFT",
      "A model that answers the way your best conversations did.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "source",
    duration: 8,
    scene: SceneSftSource,
    step: 1,
    steps: 8,
    caption: "Pick a base model and a dataset",
    captionSub: "The rows are prompt and reply pairs.",
    captionAt: "bottom-center",
    build: "The SFT source form: run name, experiment, base model, dataset.",
  },
  {
    id: 3,
    name: "hyper",
    duration: 8,
    scene: SceneSftHyper,
    step: 2,
    steps: 8,
    caption: "Or leave the defaults alone",
    captionSub: "LoRA and BF16 will get you a working run.",
    captionAt: "bottom-center",
    build: "Hyperparameters, adapter and precision switches, compute, checkpoints.",
  },
  {
    id: 4,
    name: "experiment",
    duration: 8,
    scene: SceneExperiment,
    step: 3,
    steps: 8,
    caption: "Runs group into experiments",
    captionSub: "Tick a few and their curves land on one chart.",
    captionAt: "bottom-center",
    build: "The compare surface: the run list, and three runs overlaid.",
  },
  {
    id: 5,
    name: "run",
    duration: 8,
    scene: SceneSftRun,
    step: 4,
    steps: 8,
    caption: "Watch it train",
    captionSub: "Three charts and the numbers behind them.",
    captionAt: "bottom-center",
    build: "The run detail: tabs, the train-loss curve drawing, the stat row.",
  },
  {
    id: 6,
    name: "config",
    duration: 8,
    scene: SceneSftConfig,
    step: 5,
    steps: 8,
    caption: "Everything it's running with",
    captionSub: "Compute comes first, then the hyperparameters.",
    captionAt: "bottom-center",
    build: "The Configuration tab as one scrolling column: Compute (backend, live GPU offer table, CUDA), then General, LoRA, Optimization, Schedule and MoE — every field and every default from the real form.",
  },
  {
    id: 7,
    name: "datasets",
    duration: 5,
    scene: SceneSftDatasets,
    step: 6,
    steps: 8,
    caption: "What it trained on",
    captionSub: "Both splits, and how the loader fed them in.",
    captionAt: "bottom-center",
    build: "The Datasets tab: training, validation, dataloader, sample preview.",
  },
  {
    id: 8,
    name: "checkpoints",
    duration: 5,
    scene: SceneSftCheckpoints,
    step: 7,
    steps: 8,
    caption: "Every checkpoint is kept",
    captionSub: "Resume from one, or merge the best.",
    captionAt: "bottom-center",
    build: "The Checkpoints tab: step, saved, train and eval loss, size.",
  },
  {
    id: 9,
    name: "lineage",
    duration: 5,
    scene: SceneSftLineage,
    step: 8,
    steps: 8,
    caption: "Where it came from",
    captionSub: "One hop back, and one hop forward.",
    captionAt: "bottom-center",
    build: "The Lineage tab: two parents, this run, one derived child.",
  },
  {
    id: 10,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 11,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 25 — Train with reinforcement learning.
 *
 * One job, start to finish: the agent reaches for the wrong tool, and by the
 * last shot it doesn't. Every screen follows from the one before it — the same
 * environment, the same run, the same reward climbing 0.31 → 0.79 — so this
 * is something a viewer can repeat on their own project rather than a tour of
 * what the page contains.
 */
export const T25_TRAIN_WITH_RL: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Train with reinforcement learning",
      "One GRPO run, start to finish.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "problem",
    duration: 5,
    scene: SceneRlProblem,
    caption: "It keeps calling the wrong tool",
    captionSub: "That's what we're going to fix.",
    captionAt: "bottom-center",
    build: "One failing turn: the agent calls search_orders instead of get_refund_policy.",
  },
  {
    id: 3,
    name: "environment",
    duration: 8,
    scene: SceneRlEnvironment,
    step: 1,
    steps: 12,
    caption: "First you need something to score it",
    captionSub: "Fork one from the catalogue.",
    captionAt: "bottom-center",
    build: "New environment → catalogue → Tool Use → tool-routing, added as an editable copy.",
  },
  {
    id: 4,
    name: "rubric",
    duration: 8,
    scene: SceneRlRubric,
    step: 2,
    steps: 12,
    caption: "The rubric is just Python",
    captionSub: "Wrong tool scores 0. Exactly right scores 1.",
    captionAt: "bottom-center",
    build: "The forked module: final_answer returning 0/0.5/1.0, and load_environment wrapping it in a Rubric.",
  },
  {
    id: 5,
    name: "method",
    duration: 4,
    scene: SceneRlMethod,
    step: 3,
    steps: 12,
    caption: "Start a GRPO run",
    captionSub: "This is the method that trains on a reward instead of labels.",
    captionAt: "bottom-center",
    build: "The method picker, GRPO selected, Continue.",
  },
  {
    id: 6,
    name: "form",
    duration: 8,
    scene: SceneRlForm,
    step: 4,
    steps: 12,
    caption: "Fill in the run",
    captionSub: "Then pick the environment and pin a version.",
    captionAt: "bottom-center",
    build: "The configure step: name, experiment, base model, RL mode, environment + version.",
  },
  {
    id: 7,
    name: "ruler",
    duration: 6,
    scene: SceneRlRuler,
    step: 5,
    steps: 12,
    caption: "If you can't write a rubric",
    captionSub: "RULER takes prompts instead and has a judge rank each group.",
    captionAt: "bottom-center",
    build: "The RL mode toggle in its other position: a dataset replaces the environment, and a judge ranks the group.",
  },
  {
    id: 8,
    name: "tune",
    duration: 8,
    scene: SceneRlTune,
    step: 6,
    steps: 12,
    caption: "Group size, then the GPUs",
    captionSub: "Eight attempts per prompt. Then create it and press Start.",
    captionAt: "bottom-center",
    build: "Hyperparameters and GPU allocation, with the group-size and fleet-size warnings.",
  },
  {
    id: 9,
    name: "rollouts",
    duration: 8,
    scene: SceneRlRollouts,
    step: 7,
    steps: 12,
    caption: "It tries, and gets scored",
    captionSub: "Eight goes at the same prompt.",
    captionAt: "bottom-center",
    build: "The Rollouts tab at step 20: two right, two wrong, R and A landing.",
  },
  {
    id: 10,
    name: "rollout",
    duration: 5,
    scene: SceneRlRollout,
    step: 8,
    steps: 12,
    caption: "Open one",
    captionSub: "The prompt it saw, and the answer it came up with.",
    captionAt: "bottom-center",
    build: "Attempt #0 from the list expanded: prompt turns, the tool call, the tool result, the grounded answer.",
  },
  {
    id: 11,
    name: "curve",
    duration: 5.5,
    scene: SceneRlCurve,
    step: 9,
    steps: 12,
    caption: "Reward, climbing",
    captionSub: "Watch the spread too. If it flattens there's nothing left to learn from.",
    captionAt: "bottom-center",
    build: "The Overview: six KPIs and four curves, mean reward climbing over 400 steps.",
  },
  {
    id: 12,
    name: "ship",
    duration: 5,
    scene: SceneRlShip,
    step: 10,
    steps: 12,
    caption: "Evaluate, then merge",
    captionSub: "Merging writes a model you can actually serve.",
    captionAt: "bottom-center",
    build: "The completed run's Evaluate and Merge buttons, and where the model lands.",
  },
  {
    id: 13,
    name: "deploy",
    duration: 6,
    scene: SceneRlDeploy,
    step: 11,
    steps: 12,
    caption: "Deploy it",
    captionSub: "Trained runs land in your hub, so that's where you deploy from.",
    captionAt: "bottom-center",
    build: "Deploy model: the four sources, Local Hub picked, then its form and Deploy.",
  },
  {
    id: 14,
    name: "use-it",
    duration: 5,
    scene: SceneRlUseIt,
    step: 12,
    steps: 12,
    caption: "Point the agent at it",
    captionSub: "Configure, then Model, then Serving Model.",
    captionAt: "bottom-center",
    build: "The agent's Model section: Serving Model swapped, the currently-using line, Save.",
  },
  {
    id: 15,
    name: "payoff",
    duration: 5,
    scene: SceneRlPayoff,
    caption: "Same question, right tool this time",
    captionSub: "Nothing else about the agent changed.",
    captionAt: "bottom-center",
    build: "The opening turn again, on the merged model — the correct call, first time.",
  },
  {
    id: 16,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 17,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 26 — Distill a smaller, cheaper model.
 *
 * The same shape as 25: one job, followed end to end. The agent runs on an 8B
 * that answers well and costs what an 8B costs; by the last shot it runs a 1.7B
 * that answers the same way. The numbers carry through every screen — 12,000
 * rows, 24.6M tokens, top-K 64, 9.4 GB of sidecars.
 */
export const T26_DISTILL: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Distill a smaller, cheaper model",
      "Teach a small model what a big one knows.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "problem",
    duration: 5,
    scene: SceneDistillProblem,
    caption: "Nothing wrong with the answers",
    captionSub: "It's an 8B doing work a 1.7B could do.",
    captionAt: "bottom-center",
    build: "The served model's Performance tab: throughput, latency, requests, success rate.",
  },
  {
    id: 3,
    name: "method",
    duration: 4,
    scene: SceneDistillMethod,
    step: 1,
    steps: 5,
    caption: "Start a distillation run",
    captionSub: "A big model teaches a small one.",
    captionAt: "bottom-center",
    build: "The method picker, Knowledge Distillation selected, Continue.",
  },
  {
    id: 4,
    name: "pair",
    duration: 8,
    scene: SceneDistillPair,
    step: 2,
    steps: 5,
    caption: "The base model is the student",
    captionSub: "The teacher goes in its own field, and must share the tokenizer.",
    captionAt: "bottom-center",
    build: "Run name, experiment, base model (the student), teacher model, dataset.",
  },
  {
    id: 5,
    name: "topk",
    duration: 8,
    scene: SceneDistillTopK,
    step: 3,
    steps: 5,
    caption: "How much of the teacher to keep",
    captionSub: "Every token you capture costs 6·K bytes on disk.",
    captionAt: "bottom-center",
    build: "The TOP-K & STORAGE table, 64 recommended, sized against this dataset.",
  },
  {
    id: 6,
    name: "loss",
    duration: 8,
    scene: SceneDistillLoss,
    step: 4,
    steps: 5,
    caption: "What it's optimising",
    captionSub: "Cross-entropy mixed with the teacher's own distribution.",
    captionAt: "bottom-center",
    build: "The DISTILLATION LOSS card: CE and KD rows, the weight mix, τ, the resolved objective.",
  },
  {
    id: 7,
    name: "curve",
    duration: 4.5,
    scene: SceneDistillCurve,
    step: 5,
    steps: 5,
    caption: "Watch it catch up",
    captionSub: "If eval loss follows train loss, it learned the teacher and not the rows.",
    captionAt: "bottom-center",
    build: "The Overview: four KPIs and three curves.",
  },
  {
    id: 8,
    name: "payoff",
    duration: 5,
    scene: SceneDistillPayoff,
    caption: "A quarter the size",
    captionSub: "Three times faster, and the success rate held.",
    captionAt: "bottom-center",
    build: "Teacher versus student on the numbers the film opened with.",
  },
  {
    id: 9,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 10,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 27 — Evaluate against benchmarks.
 *
 * Picks up where 26 left off: the distilled 1.7B is three times faster, and
 * nobody has checked whether it is still as good. MMLU's own catalogue copy
 * names the risk — "run after any training to verify the model hasn't lost
 * general knowledge (catastrophic forgetting check)" — so the job is to prove
 * the student held, with the teacher as the compare model.
 */
export const T27_EVALUATE: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Evaluate against benchmarks",
      "Scoring a model on public test sets.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "catalogue",
    duration: 6,
    scene: SceneEvalCatalogue,
    caption: "What a benchmark is",
    captionSub: "A test set with known answers. There are nine categories of them.",
    captionAt: "bottom-center",
    build: "The benchmark catalogue grouped by category, each with what it measures.",
  },
  {
    id: 3,
    name: "select",
    duration: 8,
    scene: SceneEvalSelect,
    step: 1,
    steps: 5,
    caption: "Choose what to test",
    captionSub: "Add as many as you want. Each one reports its own result.",
    captionAt: "bottom-center",
    build: "The Select step: the picker grouped by category, three benchmarks landing as chips.",
  },
  {
    id: 4,
    name: "configure",
    duration: 8,
    scene: SceneEvalConfigure,
    step: 2,
    steps: 5,
    caption: "Choose the model to score",
    captionSub: "Add a second one and it scores both, then reports the delta.",
    captionAt: "bottom-center",
    build: "The Configure step in the app's field order: Target, Run Name, Compare model, Subset — and why no judge field appears.",
  },
  {
    id: 5,
    name: "review",
    duration: 6,
    scene: SceneEvalReview,
    step: 3,
    steps: 5,
    caption: "Check the estimate",
    captionSub: "How many samples, how long, how much — before you commit to it.",
    captionAt: "bottom-center",
    build: "The Run step: the review card and the Estimated card, then Start.",
  },
  {
    id: 6,
    name: "result",
    duration: 6,
    scene: SceneEvalResult,
    step: 4,
    steps: 5,
    caption: "The result",
    captionSub: "It won five of seven categories, by 1.4 points.",
    captionAt: "bottom-center",
    build: "The comparison view: stat tiles, the wins-on banner, the Comparison and Result cards.",
  },
  {
    id: 7,
    name: "categories",
    duration: 6,
    scene: SceneEvalCategories,
    step: 5,
    steps: 5,
    caption: "Look at the breakdown",
    captionSub: "One category got worse. Worth knowing before you switch.",
    captionAt: "bottom-center",
    build: "The per-category table, Δ coloured by sign, one regression visible.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 28 — Bring your own compute.
 *
 * Standalone. The premise is what every training run runs into: it needs GPUs,
 * and the ones you want sit in an account you already pay for. RunPod is the
 * worked example because its connect flow is one API key, so the video spends
 * its time on the shape of the thing rather than a provider's paperwork.
 */
export const T28_COMPUTE: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Bring your own compute",
      "Connect your own cloud account, or your own servers.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "default",
    duration: 5,
    scene: SceneComputeDefault,
    caption: "Surogate provides compute by default",
    captionSub: "Eleven GPU types, from a T4 up to a B300. Nothing to set up.",
    captionAt: "bottom-center",
    build: "The compute picker with Default selected, and the GPUs it offers.",
  },
  {
    id: 3,
    name: "providers",
    duration: 6,
    scene: SceneComputeProviders,
    step: 1,
    steps: 4,
    caption: "Go to Compute → Cloud and pick a provider",
    captionSub: "Nine of them. The last is for your own servers.",
    captionAt: "bottom-center",
    build: "The provider grid with every supported cloud and its tagline.",
  },
  {
    id: 4,
    name: "connect",
    duration: 8,
    scene: SceneComputeConnect,
    step: 2,
    steps: 4,
    caption: "Paste the key and click Connect",
    captionSub: "RunPod wants one API key, with Read & Write. Each provider lists its own steps.",
    captionAt: "bottom-center",
    build: "The connect page: provider header, RunPod's instructions, the API key field, the Community Cloud switch and Connect.",
  },
  {
    id: 5,
    name: "offers",
    duration: 6,
    scene: SceneComputeOffers,
    step: 3,
    steps: 4,
    caption: "Open the backend to see its instances",
    captionSub: "Live GPU offers and prices, from your account.",
    captionAt: "bottom-center",
    build: "The backend's Available Instances table.",
  },
  {
    id: 6,
    name: "ssh",
    duration: 6,
    scene: SceneComputeSsh,
    step: 4,
    steps: 4,
    caption: "For your own hardware, pick SSH / On-prem",
    captionSub: "A user, a port, a private key and the host.",
    captionAt: "bottom-center",
    build: "The SSH form: user, port, private key, host.",
  },
  {
    id: 7,
    name: "payoff",
    duration: 6,
    scene: SceneComputePayoff,
    caption: "Now use it — for training and for serving",
    captionSub: "A run's Compute field, and a model's Deployment configuration.",
    captionAt: "bottom-center",
    build: "Both Compute fields side by side: a training run, and a served model with its Engine toggle.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 29 — Version everything in the Hub.
 *
 * Standalone. The Hub is where everything you make already lands, so the video
 * is about finding it, reading its history, pinning a version, and what that
 * pin buys you when two runs of the same job disagree.
 */
export const T29_HUB: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Version everything in the Hub",
      "Find an artefact, read its history, pin a version.",
      SEASON.develop,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "list",
    duration: 6,
    scene: SceneHubList,
    step: 1,
    steps: 4,
    caption: "Open the Data Hub",
    captionSub: "Filter by type. Models, datasets, skills, experiments, environments.",
    captionAt: "bottom-center",
    build: "The repository list with its type filters and counts.",
  },
  {
    id: 3,
    name: "repo",
    duration: 6,
    scene: SceneHubRepo,
    step: 2,
    steps: 4,
    caption: "Open a repo to see its files",
    captionSub: "Paths start with sg:// and you are always looking at one revision.",
    captionAt: "bottom-center",
    build: "The repo explorer: tabs with counts, the sg:// path, the file list.",
  },
  {
    id: 4,
    name: "commits",
    duration: 6,
    scene: SceneHubCommits,
    step: 3,
    steps: 4,
    caption: "Check Commits to see what changed",
    captionSub: "Each checkpoint the trainer wrote is its own commit.",
    captionAt: "bottom-center",
    build: "The commits timeline: short SHA, message, committer and time.",
  },
  {
    id: 5,
    name: "tags",
    duration: 6,
    scene: SceneHubTags,
    step: 4,
    steps: 4,
    caption: "Tag the one you want to keep",
    captionSub: "Then reference it as sg://repo@tag wherever you need it.",
    captionAt: "bottom-center",
    build: "The tags list and the pinned reference it produces.",
  },
  {
    id: 6,
    name: "payoff",
    duration: 5,
    scene: SceneHubPayoff,
    caption: "Why it is worth pinning",
    captionSub: "Two runs, two results, and only one of them tells you why.",
    captionAt: "bottom-center",
    build: "A pinned run and an unpinned one, scoring differently.",
  },
  {
    id: 7,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 8,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 30 — Connect Stripe and set your pricing. First of Season 4.
 *
 * The Monetize tab already ships a checklist — `SETUP_STEPS` in
 * `agent-commerce-panel.tsx` — so the video walks it. Its fifth item, sharing
 * the buy link, is video 31; this one stops where money can reach you.
 */
export const T30_STRIPE: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Connect Stripe and set your pricing",
      "Take payment for an agent, into your own account.",
      SEASON.monetize,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "checklist",
    duration: 6,
    scene: SceneStripeChecklist,
    caption: "Open the Monetize tab",
    captionSub: "It lists what has to happen, and ticks each one off.",
    captionAt: "bottom-center",
    build: "The five-step setup checklist as the page presents it.",
  },
  {
    id: 3,
    name: "connect",
    duration: 6,
    scene: SceneStripeConnect,
    step: 1,
    steps: 5,
    caption: "Click Connect Stripe",
    captionSub: "Do the identity and bank form in the tab it opens, then come back.",
    captionAt: "bottom-center",
    build: "The Stripe Connect card flipping from Not connected to Active.",
  },
  {
    id: 4,
    name: "pricing",
    duration: 6,
    scene: SceneStripePricing,
    step: 2,
    steps: 5,
    caption: "Choose a pricing model",
    captionSub: "Subscriptions, one-time packs, both, or free.",
    captionAt: "bottom-center",
    build: "The four pricing modes with their descriptions, Subscription picked.",
  },
  {
    id: 5,
    name: "offer",
    duration: 8,
    scene: SceneStripeOffer,
    step: 3,
    steps: 5,
    caption: "Add an offer",
    captionSub: "A name, a price, and how much usage it includes.",
    captionAt: "bottom-center",
    build: "The offer editor with the usage explainer written for non-AI builders.",
  },
  {
    id: 6,
    name: "buy-page",
    duration: 8,
    scene: SceneStripeBuyPage,
    step: 4,
    steps: 5,
    caption: "This is the page buyers open",
    captionSub: "Your offer, rendered as a card. Subscribe hands off to Stripe Checkout.",
    captionAt: "bottom-center",
    build: "The buy page: agent name, the free-trial note, the offer card and its Subscribe button.",
  },
  {
    id: 7,
    name: "after",
    duration: 6,
    scene: SceneStripeAfter,
    step: 5,
    steps: 5,
    caption: "And what happens once they pay",
    captionSub: "The page waits for Stripe's webhook, then opens the chat.",
    captionAt: "bottom-center",
    build: "The activation banner turning into an active subscription and Manage subscription.",
  },
  {
    id: 8,
    name: "live",
    duration: 5,
    scene: SceneStripeLive,
    caption: "Four down, one to go",
    captionSub: "Payments work. Nobody has the link yet.",
    captionAt: "bottom-center",
    build: "The checklist with the first four ticked.",
  },
  {
    id: 9,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 10,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 31 — Your agent's landing page and buy link.
 *
 * Standalone. Video 30 priced the agent; this is about the page that pricing
 * produced — its address, how it looks, and the two ways to put it in front of
 * someone.
 */
export const T31_BUY_LINK: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "Your agent's landing page and buy link",
      "Build the page, publish it, send the link.",
      SEASON.monetize,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "identity",
    duration: 6,
    scene: SceneIdentity,
    step: 1,
    steps: 6,
    caption: "Start on the Identity tab",
    captionSub: "The name is the page title. The description sits under it.",
    captionAt: "bottom-center",
    build: "Basic info: Name, the locked Slug with its Rename toggle, Description.",
  },
  {
    id: 3,
    name: "layouts",
    duration: 6,
    scene: SceneLandingLayouts,
    step: 2,
    steps: 6,
    caption: "Start the page from a layout",
    captionSub: "Preview first — applying replaces what's there.",
    captionAt: "bottom-center",
    build: "The Layouts list with each layout's block stack and a Preview button.",
  },
  {
    id: 4,
    name: "blocks",
    duration: 6,
    scene: SceneLandingBlocks,
    step: 3,
    steps: 6,
    caption: "Or add blocks yourself",
    captionSub: "Eight kinds. Up to 32 on a page.",
    captionAt: "bottom-center",
    build: "The Add-a-block dialog with all eight kinds and their blurbs.",
  },
  {
    id: 5,
    name: "theme",
    duration: 6,
    scene: SceneBuyLinkTheme,
    step: 4,
    steps: 6,
    caption: "Pick how it looks",
    captionSub: "Six themes. The landing page and the buy page use the same one.",
    captionAt: "bottom-center",
    build: "The Storefront look picker with all six themes and their swatches.",
  },
  {
    id: 6,
    name: "publish",
    duration: 6,
    scene: SceneLandingPublish,
    step: 5,
    steps: 6,
    caption: "Switch it Live",
    captionSub: "Until you do, the link returns not found.",
    captionAt: "bottom-center",
    build: "The landing link card and the Live / Off switch.",
  },
  {
    id: 7,
    name: "rendered",
    duration: 8,
    scene: SceneLandingRendered,
    caption: "The published page",
    captionSub: "What the landing link opens.",
    captionAt: "bottom-center",
    build: "The landing page rendered: hero, features and a section band, in Midnight.",
  },
  {
    id: 8,
    name: "share",
    duration: 6,
    scene: SceneBuyLinkShare,
    step: 6,
    steps: 6,
    caption: "Copy the buy link",
    captionSub: "It uses the agent's slug when it has one.",
    captionAt: "bottom-center",
    build: "The share card, its URL, and Copy link turning into Copied.",
  },
  {
    id: 9,
    name: "page",
    duration: 6,
    scene: SceneBuyLinkPage,
    caption: "Open the buy link",
    captionSub: "Your offer, same theme.",
    captionAt: "bottom-center",
    build: "The buy page rendered in Midnight.",
  },
  {
    id: 10,
    name: "embed",
    duration: 6,
    scene: SceneBuyLinkEmbed,
    caption: "Or embed it on your own site",
    captionSub: "Add your domain, copy the snippet. Other domains can't load it.",
    captionAt: "bottom-center",
    build: "The embed panel: origin allowlist, generated snippet, Copy.",
  },
  {
    id: 11,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 12,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/**
 * 32 — What a buyer sees. Last of the catalogue.
 *
 * Every shot is a buyer's screen, so every shot is drawn in the agent's own
 * theme rather than the studio's white panels.
 */
export const T32_BUYER: Shot[] = [
  {
    id: 1,
    name: "title",
    duration: 3,
    scene: titleCard(
      "What a buyer sees",
      "The same agent, from the other side.",
      SEASON.monetize,
    ),
    build: "Opening card.",
  },
  {
    id: 2,
    name: "land",
    duration: 6,
    scene: SceneBuyerLand,
    step: 1,
    steps: 6,
    caption: "They open the buy link",
    captionSub: "Name, description, the free trial, and your offer.",
    captionAt: "bottom-center",
    build: "The buy page signed out, with the Sign in button and the offer card.",
  },
  {
    id: 3,
    name: "signin",
    duration: 5,
    scene: SceneBuyerSignIn,
    step: 2,
    steps: 6,
    caption: "They sign in",
    captionSub: "Email and password, against your Firebase project.",
    captionAt: "bottom-center",
    build: "The sign-in card: email, password, Create an account.",
  },
  {
    id: 4,
    name: "checkout",
    duration: 6,
    scene: SceneBuyerCheckout,
    step: 3,
    steps: 6,
    caption: "Subscribe sends them to Stripe",
    captionSub: "The card details are entered on Stripe, not on your page.",
    captionAt: "bottom-center",
    build: "Subscribe turning into Redirecting…, then Stripe Checkout.",
  },
  {
    id: 5,
    name: "activating",
    duration: 5,
    scene: SceneBuyerActivating,
    step: 4,
    steps: 6,
    caption: "They come back",
    captionSub: "The page waits for the webhook, then shows the subscription.",
    captionAt: "bottom-center",
    build: "The activation banner turning into an active subscription.",
  },
  {
    id: 6,
    name: "chat",
    duration: 8,
    scene: SceneBuyerChat,
    step: 5,
    steps: 6,
    caption: "They chat",
    captionSub: "The balance sits in the header and drops as they send.",
    captionAt: "bottom-center",
    build: "The buyer chat: header, balance, one turn, the message box.",
  },
  {
    id: 7,
    name: "renew",
    duration: 6,
    scene: SceneBuyerRenew,
    step: 6,
    steps: 6,
    caption: "They run low",
    captionSub: "Packs top them up. Subscribing twice is refused.",
    captionAt: "bottom-center",
    build: "The return visit: balance low, a top-up pack, the already-subscribed note.",
  },
  {
    id: 8,
    name: "next-steps",
    duration: 5,
    scene: nextStepsCard(NEXT_STEPS, "and so much more…."),
    caption: "Everything else it can do",
    captionAt: "bottom-center",
    build: "The capability board.",
  },
  {
    id: 9,
    name: "brand",
    duration: 2,
    scene: brandCard(),
    build: "Closing brand card.",
  },
];

/** Every tutorial cut, by composition id. */
export const TUTORIALS = {
  "t01-create-agent": T01_CREATE_AGENT,
  "t02-add-knowledge": T02_ADD_KNOWLEDGE,
  "t03-add-skills": T03_ADD_SKILLS,
  "t04-connect-tools": T04_CONNECT_TOOLS,
  "t05-put-it-in-slack": T05_PUT_IT_IN_SLACK,
  "t06-hand-it-a-mission": T06_HAND_IT_A_MISSION,
  "t07-use-a-browser": T07_USE_A_BROWSER,
  "t08-read-a-session": T08_READ_A_SESSION,
  "t09-correct-and-redeploy": T09_CORRECT_AND_REDEPLOY,
  "t10-deep-research": T10_DEEP_RESEARCH,
  "t11-research-missions": T11_RESEARCH_MISSIONS,
  "t12-coding-agents": T12_CODING_AGENTS,
  "t13-loops": T13_LOOPS,
  "t14-whiteboard": T14_WHITEBOARD,
  "t15-goals": T15_GOALS,
  "t16-approvals": T16_APPROVALS,
  "t17-governance": T17_GOVERNANCE,
  "t18-web-app": T18_WEB_APP,
  "t19-users": T18_USERS,
  "t20-deploy-a-model": T20_DEPLOY_A_MODEL,
  "t21-build-a-dataset": T21_BUILD_A_DATASET,
  "t23-synthetic": T23_SYNTHETIC,
  "t24-sft": T24_SFT,
  "t25-train-with-rl": T25_TRAIN_WITH_RL,
  "t26-distill": T26_DISTILL,
  "t27-evaluate": T27_EVALUATE,
  "t28-compute": T28_COMPUTE,
  "t29-hub": T29_HUB,
  "t30-stripe": T30_STRIPE,
  "t31-buy-link": T31_BUY_LINK,
  "t32-buyer": T32_BUYER,
} as const;
